### PR TITLE
Update docs to returned JSON

### PR DESCRIPTION
**Pull request by vincentwolsink**
Due to changes in https://github.com/ByteInternet/hypernode-api/pull/494

### CODE REVIEW

**Review by kerrermanisNL — APPROVED** [review]
Happy with it for now. We'll probably change this around in the future anyway. Just to make sure, this isn't actually something that is really used by you or anything right? ;)

**Comment by vincentwolsink** [comment]
Sorry, what do you mean? I am using it here: https://github.com/ByteInternet/hypernode-auth/pull/70

**Comment by kerrermanisNL** [comment]
I mean the login URL isn't something people are going to use to buy stuff on your credit ;P

**Comment by vincentwolsink** [comment]
Ah.. 🙂 No, the token is a sample token I got from the documentation page of Chargebee.

**Pull request merged**
